name: Jekyll site CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Directories
        run: |
          mkdir -p /github/workspace/_site
          mkdir -p /github/workspace/_site/assets

      - name: Check Directory Ownership
        run: |
          docker run \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest /bin/bash -c "ls -la /srv/jekyll /srv/jekyll/_site"

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
